const path = require("path");

module.exports = {
    darkMode: "class",
    presets: [require("@medusajs/ui-preset")],
    content: [
        "./src/app/**/*.{js,ts,jsx,tsx}",
        "./src/pages/**/*.{js,ts,jsx,tsx}",
        "./src/components/**/*.{js,ts,jsx,tsx}",
        "./src/modules/**/*.{js,ts,jsx,tsx}",
        "./node_modules/@medusajs/ui/dist/**/*.{js,jsx,ts,tsx}",
    ],
    theme: {
        extend: {
            transitionProperty: {
                width: "width margin",
                height: "height",
                bg: "background-color",
                display: "display opacity",
                visibility: "visibility",
                padding:
                    "padding-top padding-right padding-bottom padding-left",
            },
            colors: {
                // Industrial palette - primary (deep blue), accent (orange), neutral (slate)
                primary: {
                    50: "#eff6ff",
                    100: "#dbeafe",
                    200: "#bfdbfe",
                    300: "#93c5fd",
                    400: "#60a5fa",
                    500: "#1E3A8A",
                    600: "#1e40af",
                    700: "#1d4ed8",
                    800: "#1e3a8a",
                    900: "#1e3a5f",
                    950: "#0f172a",
                },
                accent: {
                    50: "#fff7ed",
                    100: "#ffedd5",
                    200: "#fed7aa",
                    300: "#fdba74",
                    400: "#fb923c",
                    500: "#F97316",
                    600: "#ea580c",
                    700: "#c2410c",
                    800: "#9a3412",
                    900: "#7c2d12",
                    950: "#431407",
                },
                neutral: {
                    50: "#f8fafc",
                    100: "#f1f5f9",
                    200: "#e2e8f0",
                    300: "#cbd5e1",
                    400: "#94a3b8",
                    500: "#64748b",
                    600: "#475569",
                    700: "#334155",
                    800: "#1e293b",
                    900: "#0f172a",
                    950: "#020617",
                },
                grey: {
                    0: "#FFFFFF",
                    5: "#F9FAFB",
                    10: "#F3F4F6",
                    20: "#E5E7EB",
                    30: "#D1D5DB",
                    40: "#9CA3AF",
                    50: "#6B7280",
                    60: "#4B5563",
                    70: "#374151",
                    80: "#1F2937",
                    90: "#111827",
                },
                // New palette - deep twilight (primary dark)
                "deep-twilight": {
                    50: "#e6e7fe",
                    100: "#cecefd",
                    200: "#9c9efc",
                    300: "#6b6dfa",
                    400: "#393cf9",
                    500: "#080cf7",
                    600: "#0609c6",
                    700: "#050794",
                    800: "#030563",
                    900: "#020231",
                    950: "#010223",
                },
                "bright-teal-blue": {
                    50: "#e5f6ff",
                    100: "#ccedff",
                    200: "#99dbff",
                    300: "#66c9ff",
                    400: "#33b8ff",
                    500: "#00a6ff",
                    600: "#0085cc",
                    700: "#006399",
                    800: "#004266",
                    900: "#002133",
                    950: "#001724",
                },
                "turquoise-surf": {
                    50: "#e5fbff",
                    100: "#ccf6ff",
                    200: "#99eeff",
                    300: "#66e5ff",
                    400: "#33ddff",
                    500: "#00d4ff",
                    600: "#00aacc",
                    700: "#007f99",
                    800: "#005566",
                    900: "#002a33",
                    950: "#001e24",
                },
                "frosted-blue": {
                    50: "#e9f9fc",
                    100: "#d2f3f9",
                    200: "#a6e7f2",
                    300: "#79dbec",
                    400: "#4ccfe6",
                    500: "#20c2df",
                    600: "#199cb3",
                    700: "#137586",
                    800: "#0d4e59",
                    900: "#06272d",
                    950: "#041b1f",
                },
                "light-cyan": {
                    50: "#e8f9fc",
                    100: "#d2f3f9",
                    200: "#a5e6f3",
                    300: "#78daed",
                    400: "#4acde8",
                    500: "#1dc1e2",
                    600: "#179ab5",
                    700: "#127487",
                    800: "#0c4d5a",
                    900: "#06272d",
                    950: "#041b20",
                },
                // Aliases for backward compatibility - map to new palette
                space_indigo: {
                    DEFAULT: "#050794",
                    100: "#010223",
                    200: "#020231",
                    300: "#030563",
                    400: "#050794",
                    500: "#0609c6",
                    600: "#080cf7",
                    700: "#393cf9",
                    800: "#6b6dfa",
                    900: "#9c9efc",
                },
                dusty_grape: {
                    DEFAULT: "#0085cc",
                    100: "#001724",
                    200: "#002133",
                    300: "#004266",
                    400: "#006399",
                    500: "#0085cc",
                    600: "#00a6ff",
                    700: "#33b8ff",
                    800: "#66c9ff",
                    900: "#99dbff",
                },
                lilac_ash: {
                    DEFAULT: "#20c2df",
                    100: "#041b1f",
                    200: "#06272d",
                    300: "#0d4e59",
                    400: "#137586",
                    500: "#199cb3",
                    600: "#20c2df",
                    700: "#4ccfe6",
                    800: "#79dbec",
                    900: "#a6e7f2",
                },
                almond_silk: {
                    DEFAULT: "#c9ada7",
                    100: "#2e1f1c",
                    200: "#5b3e38",
                    300: "#895d54",
                    400: "#ad8279",
                    500: "#c9ada7",
                    600: "#d4bdb8",
                    700: "#dececa",
                    800: "#e9dedc",
                    900: "#f4efed",
                },
                parchment: {
                    DEFAULT: "#e8f9fc",
                    100: "#041b20",
                    200: "#06272d",
                    300: "#0c4d5a",
                    400: "#127487",
                    500: "#179ab5",
                    600: "#d2f3f9",
                    700: "#a5e6f3",
                    800: "#78daed",
                    900: "#4acde8",
                },
                sales: {
                    DEFAULT: "#9e2a2b",
                    50: "#fef2f2",
                    100: "#fee2e2",
                    200: "#fecaca",
                    300: "#fca5a5",
                    400: "#f87171",
                    500: "#9e2a2b",
                    600: "#7f1d1d",
                    700: "#651818",
                    800: "#4c1414",
                    900: "#3c1010",
                },
            },
            borderRadius: {
                none: "0px",
                soft: "2px",
                base: "4px",
                rounded: "8px",
                large: "16px",
                circle: "9999px",
            },
            maxWidth: {
                "8xl": "100rem",
            },
            screens: {
                "2xsmall": "320px",
                xsmall: "512px",
                small: "1024px",
                medium: "1280px",
                large: "1440px",
                xlarge: "1680px",
                "2xlarge": "1920px",
            },
            fontSize: {
                "3xl": "2rem",
            },
            fontFamily: {
                sans: [
                    "Inter",
                    "-apple-system",
                    "BlinkMacSystemFont",
                    "Segoe UI",
                    "Roboto",
                    "Helvetica Neue",
                    "Ubuntu",
                    "sans-serif",
                ],
            },
            keyframes: {
                ring: {
                    "0%": { transform: "rotate(0deg)" },
                    "100%": { transform: "rotate(360deg)" },
                },
                "fade-in-right": {
                    "0%": {
                        opacity: "0",
                        transform: "translateX(10px)",
                    },
                    "100%": {
                        opacity: "1",
                        transform: "translateX(0)",
                    },
                },
                "fade-in-top": {
                    "0%": {
                        opacity: "0",
                        transform: "translateY(-10px)",
                    },
                    "100%": {
                        opacity: "1",
                        transform: "translateY(0)",
                    },
                },
                "fade-out-top": {
                    "0%": {
                        height: "100%",
                    },
                    "99%": {
                        height: "0",
                    },
                    "100%": {
                        visibility: "hidden",
                    },
                },
                "accordion-slide-up": {
                    "0%": {
                        height: "var(--radix-accordion-content-height)",
                        opacity: "1",
                    },
                    "100%": {
                        height: "0",
                        opacity: "0",
                    },
                },
                "accordion-slide-down": {
                    "0%": {
                        "min-height": "0",
                        "max-height": "0",
                        opacity: "0",
                    },
                    "100%": {
                        "min-height": "var(--radix-accordion-content-height)",
                        "max-height": "none",
                        opacity: "1",
                    },
                },
                enter: {
                    "0%": { transform: "scale(0.9)", opacity: 0 },
                    "100%": { transform: "scale(1)", opacity: 1 },
                },
                leave: {
                    "0%": { transform: "scale(1)", opacity: 1 },
                    "100%": { transform: "scale(0.9)", opacity: 0 },
                },
                "slide-in": {
                    "0%": { transform: "translateY(-100%)" },
                    "100%": { transform: "translateY(0)" },
                },
            },
            animation: {
                ring: "ring 2.2s cubic-bezier(0.5, 0, 0.5, 1) infinite",
                "fade-in-right":
                    "fade-in-right 0.3s cubic-bezier(0.5, 0, 0.5, 1) forwards",
                "fade-in-top":
                    "fade-in-top 0.2s cubic-bezier(0.5, 0, 0.5, 1) forwards",
                "fade-out-top":
                    "fade-out-top 0.2s cubic-bezier(0.5, 0, 0.5, 1) forwards",
                "accordion-open":
                    "accordion-slide-down 300ms cubic-bezier(0.87, 0, 0.13, 1) forwards",
                "accordion-close":
                    "accordion-slide-up 300ms cubic-bezier(0.87, 0, 0.13, 1) forwards",
                enter: "enter 200ms ease-out",
                "slide-in": "slide-in 1.2s cubic-bezier(.41,.73,.51,1.02)",
                leave: "leave 150ms ease-in forwards",
        },
    },
    plugins: [require("tailwindcss-radix")()],
}}
